spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logical-thinking
    username: postgres
    password: postgres
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:/jp/co/runy/logical_thinking/mapper/*.xml